### ISSUE TITLE
nodeList not iterable in older browsers causing error

### ISSUE THREAD

**Issue by RobMaple** [argyleink/blingblingjs#13]
I'm getting an error in Safari 9 (although presumably this applies to similarly old browsers) due to the use of the spread operator on line 37. 

This issue appears after transpilation with Babel and seems to be due to nodeLists not being iterable in older browsers.

`[...$nodes].map($el => Object.assign($el, sugar)), `

A quick fix would be to wrap `$nodes` in `Array.from(...)` although I'm not sure at first glance if that would break anything. 

Happy to submit a PR if that seems like a viable fix.

**Comment by argyleink** [comment]
i've [made a little playground here](https://glitch.com/edit/#!/argyleink-blingblingjs), you can "remix" and make edits if you want. or [test the hosted demo](https://argyleink-blingblingjs.glitch.me) in safari 9 to see if it fixes it

is this issue with babel or with blingbling though? curious why that detail was included since the snippet shown is as authored

i wrapped $nodes in Array.from() [in that glitch](https://glitch.com/edit/#!/argyleink-blingblingjs?path=src/index.js:37:4), everything looks to work as it did before. give this a shot in your broken env, see if it's resolved! https://argyleink-blingblingjs.glitch.me 

if you find it's fixed, then yeah, i think you deserve to land the correction. thanks for the report! what a quark.

**Comment by RobMaple** [comment]
Just to clarify Re. Babel (sorry, wasn't particularly clear why I mentioned it) -- this was just to point out that the issue was unrelated to the fact that not all ES6 works great in Safari 9 as the code had been transpiled so was confident the issue was NodeList related.

Thanks for setting up those demos. I had to tweak it slightly as some of the ES6 sytax was causing sepparate issues but once that was sorted it all works great! 

Will submit a PR with the ammend :)

**Comment by argyleink** [comment]
closed by #14
