### ISSUE TITLE
$.once()

### ISSUE THREAD

**Issue by argyleink** [argyleink/blingblingjs#6]
one time event shorthand

**Comment by hchiam** [comment]
i'd be interested in setting this up. at first glance, i'd think it should be equivalent to adding an event, and then once it's run, remove the event. to make sure i'm on the right track, is it like jQuery's [`.one()`](https://api.jquery.com/one/) or more like some version of [`.once()`](https://www.drupal.org/project/drupal/issues/444344)?

**Comment by argyleink** [comment]
it's like `.on()` but instead of only passing 2 params along to [adding the event listener](https://github.com/argyleink/blingblingjs/blob/master/src/index.js#L6), it'd auto [add the built in](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#:~:text=the%20DOM%20tree.-,once,-A%20boolean%20value)

```js
element.addEventListener(eventNameParam, callbackParam, { once:true }) // options object preconfigured
```

this could be mitigated tho if options could be passed at all, less api surface area and adds more dev facing capability. maybe we just add support for the options object on event listeners?

**Comment by hchiam** [comment]
I like your idea of adding an options object. 

We could add an optional 3rd param to both the `.on()` and `.off()`: https://github.com/argyleink/blingblingjs/blob/master/src/index.js (`addEventListener` and `removeEventListener`) and also detect whether it's an object vs boolean, to cover the capture param too (#4) (EDIT: or just pass a 3rd param it turns out)
